### ISSUE TITLE
type.css file should not be changed 

### ISSUE THREAD

**Issue by sent0007** [sent0007/content-page#1]
Is there a way to grab the original type.css file from this repository ? At some point I must have altered it and saved over it and now its causing a markbot error.

thank you!
@mackenzierose

**Comment by MacKenzieRose** [comment]
If you copy and paste all the content from [this page](https://raw.githubusercontent.com/acgd-webdev-2/content-page/gh-pages/css/type.css) into your type file, that should fix it.

Cheers!

MacKenzie

**Comment by sent0007** [comment]
Thank you, that worked great!
